version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ğŸ˜‘ dependencies"
      - "ğŸ‹ docker"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ğŸ˜‘ dependencies"
      - "ğŸ§‘â€ğŸ’» github actions"
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ğŸ˜‘ dependencies"
      - "ğŸ˜ php"
