version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
    labels:
      - "ğŸ˜‘ dependencies"
      - "ğŸ‹ docker"
    reviewers:
      - "alexjustesen"
    commit-message:
      prefix: "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
    labels:
      - "ğŸ˜‘ dependencies"
      - "ğŸ§‘â€ğŸ’» github actions"
    reviewers:
      - "alexjustesen"
    commit-message:
      prefix: "gh actions"
