---
authentication: true
influxdb:
  enabled: false
  version: 2 # Only InfluxDB2 is supported right now
  url: 'http://your-influxdb-instance' # Full url to your InfluxDB instance, sometimes this includes a port number
  org: '' # Organization name, usually created when you installed InfluxDB
  bucket: 'speedtest-tracker' # A name location to store the speedtest data in
  token: '' # This is your API token
notifications:
  channels:
    discord:
      webhook_url: null # Set as null to disable
    slack:
      webhook_url: null # Set as null to disable
speedtest:
  enabled: true
  schedule: '*/60 * * * *' # every hour
  ookla_server_id: null # specify a server ID to use a specific server
tz: 'UTC'
