blank_issues_enabled: false
contact_links:
  - name: Translations
    url: https://crowdin.com/project/speedtest-tracker
    about: Please report translation issues and request new translations here. 
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
